name: RulesCommands
description: Addon for Rules plugin which let your react to accept/deny with commands.
version: 0.1

author: arboriginal
website: https://github.com/arboriginal/RulesCommands
dev-url: https://github.com/arboriginal/RulesCommands

depend: [ Rules ]
softdepend: [ ]

api-version: 1.13
database: false

main: me.arboriginal.RulesCommands.Main

commands:
  rulescmds-reload:
    description: Reload RulesCommands configuration
    permission: rulescmds.reload

permissions:
  rulescmds.reload:
    description: Allows to reload the configuration.
    default: op
